[package]
name = "aiui-aix-pack"
version = "0.10.1"
edition = "2021"
description = "Cross-platform in-memory packer and optimizer for AIX artifacts"
license = "MIT"
repository = "https://github.com/jsar-project/aix"

[dependencies]
aix = { package = "aiui-aix", path = "../aix", version = "0.10.1" }
anyhow = { workspace = true }
chardetng = "0.1"
encoding_rs = "0.8"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
ignore = "0.4"
oxc_allocator = "0.139"
oxc_ast = "0.139"
oxc_ast_visit = "0.139"
oxc_codegen = "0.139"
oxc_minifier = "0.139"
oxc_parser = "0.139"
oxc_span = "0.139"
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[dev-dependencies]
uuid = { version = "1.0", features = ["v4"] }
criterion = "0.5"

[[bench]]
name = "pack"
harness = false
