use anyhow::{anyhow, Result};
use chardetng::EncodingDetector;
use encoding_rs::{GB18030, UTF_16BE, UTF_16LE, UTF_8};
use image::codecs::jpeg::JpegEncoder;
use image::codecs::png::{CompressionType, FilterType, PngEncoder};
use image::ImageEncoder;
use oxc_allocator::Allocator;
use oxc_codegen::{Codegen, CodegenOptions};
use oxc_minifier::{CompressOptions, MangleOptions, Minifier, MinifierOptions};
use oxc_parser::Parser;
use oxc_span::SourceType;
use serde::{Deserialize, Serialize};
use std::io::{Cursor, Write};
use std::path::Path;
use zip::write::FileOptions;

pub mod check;
pub mod collector;

const UTF8_TEXT_EXTENSIONS: &[&str] = &["ink"];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InputFile {
    pub path: String,
    pub data: Vec<u8>,
}

impl InputFile {
    pub fn new(path: impl Into<String>, data: impl Into<Vec<u8>>) -> Self {
        Self {
            path: path.into(),
            data: data.into(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct OptimizeOptions {
    pub level: u8,
    pub json: bool,
    pub png: bool,
    pub jpeg: bool,
}

impl Default for OptimizeOptions {
    fn default() -> Self {
        Self {
            level: 2,
            json: true,
            png: true,
            jpeg: true,
        }
    }
}

#[derive(Clone)]
pub struct PackOptions<'a> {
    pub build_id: String,
    pub engine: Option<String>,
    pub optimize: Option<OptimizeOptions>,
    pub signing_key: Option<&'a aix::crypto::PrivateKey>,
}

impl<'a> PackOptions<'a> {
    pub fn new(build_id: impl Into<String>) -> Self {
        Self {
            build_id: build_id.into(),
            engine: None,
            optimize: None,
            signing_key: None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum OptimizeStatus {
    Optimized,
    Unchanged,
    Skipped,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileOptimizeReport {
    pub path: String,
    pub status: OptimizeStatus,
    pub original_size: u64,
    pub output_size: u64,
    pub saved_bytes: u64,
    pub converted_to_utf8: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum PackProgressEvent {
    TransferringFilesToWasm,
    CollectingSourceInputs,
    ResolvingEngine,
    PreparingFiles,
    FileFinished { report: FileOptimizeReport },
    FinalizingArchive,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OptimizeReport {
    pub files: Vec<FileOptimizeReport>,
    pub original_size: u64,
    pub output_size: u64,
    pub saved_bytes: u64,
}

#[derive(Debug)]
pub struct PackOutput {
    pub data: Vec<u8>,
    pub report: OptimizeReport,
    pub warnings: Vec<String>,
}

#[derive(Debug)]
struct PreparedFile {
    data: Vec<u8>,
    converted_to_utf8: bool,
    optimized: bool,
    supported: bool,
}

pub fn pack(mut files: Vec<InputFile>, options: PackOptions<'_>) -> Result<PackOutput> {
    if options.build_id.is_empty() {
        return Err(anyhow!("build_id must not be empty"));
    }
    if files.iter().any(|file| file.path == "VERSION") {
        return Err(anyhow!("VERSION is generated by the packer"));
    }
    files.sort_by(|a, b| a.path.as_bytes().cmp(b.path.as_bytes()));
    validate_paths(&files)?;
    let warnings = validate_app_config(&files)?;
    let engine = resolve_engine_range(&files, options.engine.as_deref())?;
    aix::crypto::validate_engine_range(&engine)
        .map_err(|error| anyhow!("invalid engine range: {}", error))?;

    let mut entries = Vec::with_capacity(files.len() + 1);
    entries.push(InputFile::new("VERSION", options.build_id.into_bytes()));
    entries.extend(files);
    let mut output = pack_entries(
        entries,
        options.optimize.as_ref(),
        &engine,
        options.signing_key,
        |_| Ok(()),
    )?;
    output.warnings = warnings;
    Ok(output)
}

pub fn optimize_package(data: &[u8], options: &OptimizeOptions) -> Result<PackOutput> {
    let reader = aix::AixReader::new(data.to_vec())?;
    let engine = reader.get_engine().unwrap_or_else(|| "*".into());
    let mut entries = Vec::with_capacity(reader.list().len());
    for entry in reader.list() {
        if entry.name.ends_with('/') || entry.name.starts_with("META-INF/aix/") {
            continue;
        }
        entries.push(InputFile::new(&entry.name, reader.read_file(&entry.name)?));
    }
    pack_entries(entries, Some(options), &engine, None, |_| Ok(()))
}

pub fn pack_with_progress<F>(
    mut files: Vec<InputFile>,
    options: PackOptions<'_>,
    mut progress: F,
) -> Result<PackOutput>
where
    F: FnMut(PackProgressEvent) -> Result<()>,
{
    if options.build_id.is_empty() {
        return Err(anyhow!("build_id must not be empty"));
    }
    if files.iter().any(|file| file.path == "VERSION") {
        return Err(anyhow!("VERSION is generated by the packer"));
    }
    files.sort_by(|a, b| a.path.as_bytes().cmp(b.path.as_bytes()));
    validate_paths(&files)?;
    let warnings = validate_app_config(&files)?;
    progress(PackProgressEvent::ResolvingEngine)?;
    let engine = resolve_engine_range(&files, options.engine.as_deref())?;
    aix::crypto::validate_engine_range(&engine)
        .map_err(|error| anyhow!("invalid engine range: {}", error))?;

    let mut entries = Vec::with_capacity(files.len() + 1);
    entries.push(InputFile::new("VERSION", options.build_id.into_bytes()));
    entries.extend(files);
    let mut output = pack_entries(
        entries,
        options.optimize.as_ref(),
        &engine,
        options.signing_key,
        progress,
    )?;
    output.warnings = warnings;
    Ok(output)
}

fn pack_entries<F>(
    mut files: Vec<InputFile>,
    optimize: Option<&OptimizeOptions>,
    engine: &str,
    signing_key: Option<&aix::crypto::PrivateKey>,
    mut progress: F,
) -> Result<PackOutput>
where
    F: FnMut(PackProgressEvent) -> Result<()>,
{
    files.sort_by(|a, b| a.path.as_bytes().cmp(b.path.as_bytes()));
    validate_paths(&files)?;

    let mut report = OptimizeReport::default();
    let mut prepared_files = Vec::with_capacity(files.len() + 3);
    progress(PackProgressEvent::PreparingFiles)?;

    for file in files {
        let original_size = file.data.len() as u64;
        let prepared = prepare_file(&file.path, file.data, optimize)?;
        let output_size = prepared.data.len() as u64;
        let saved_bytes = original_size.saturating_sub(output_size);
        report.original_size += original_size;
        report.output_size += output_size;
        report.saved_bytes += saved_bytes;
        let file_report = FileOptimizeReport {
            path: file.path.clone(),
            status: if prepared.optimized {
                OptimizeStatus::Optimized
            } else if prepared.supported {
                OptimizeStatus::Unchanged
            } else {
                OptimizeStatus::Skipped
            },
            original_size,
            output_size,
            saved_bytes,
            converted_to_utf8: prepared.converted_to_utf8,
        };
        progress(PackProgressEvent::FileFinished {
            report: file_report.clone(),
        })?;
        report.files.push(file_report);

        prepared_files.push(InputFile::new(file.path, prepared.data));
    }

    progress(PackProgressEvent::FinalizingArchive)?;
    let manifest = build_manifest(&prepared_files, engine, signing_key);
    let manifest_data = serde_json::to_vec(&manifest)?;
    if let Some(key) = signing_key {
        let signature = key.sign(b"package-manifest", &manifest_data);
        prepared_files.push(InputFile::new(
            aix::crypto::SIGNATURE_PATH,
            signature.to_bytes(),
        ));
        prepared_files.push(InputFile::new(
            aix::crypto::PUBLIC_KEY_PATH,
            key.public_key().to_bytes(),
        ));
    }
    prepared_files.push(InputFile::new(aix::crypto::MANIFEST_PATH, manifest_data));
    prepared_files.sort_by(|a, b| a.path.as_bytes().cmp(b.path.as_bytes()));

    let cursor = Cursor::new(Vec::new());
    let mut zip = zip::ZipWriter::new(cursor);
    for file in prepared_files {
        let file_options = FileOptions::default()
            .compression_method(compression_method_for(&file.path))
            .unix_permissions(0o644);
        zip.start_file(file.path, file_options)?;
        zip.write_all(&file.data)?;
    }

    Ok(PackOutput {
        data: zip.finish()?.into_inner(),
        report,
        warnings: Vec::new(),
    })
}

/// Chooses the ZIP compression method for a packed entry.
///
/// Image formats re-encoded by the optimizer are already compressed, so
/// deflating them again wastes CPU without shrinking the package. Everything
/// else — JSON, scripts, templates, stylesheets, and the generated manifest —
/// compresses well.
fn compression_method_for(path: &str) -> zip::CompressionMethod {
    if is_already_compressed(path) {
        zip::CompressionMethod::Stored
    } else {
        zip::CompressionMethod::Deflated
    }
}

fn is_already_compressed(path: &str) -> bool {
    matches!(
        path.rsplit_once('.')
            .map(|(_, extension)| extension)
            .unwrap_or("")
            .to_ascii_lowercase()
            .as_str(),
        "png" | "jpg" | "jpeg"
    )
}

fn build_manifest(
    files: &[InputFile],
    engine: &str,
    signing_key: Option<&aix::crypto::PrivateKey>,
) -> aix::crypto::PackageManifest {
    let mut entries = Vec::with_capacity(files.len());
    let mut version = String::new();
    for file in files {
        if file.path == "VERSION" {
            version = String::from_utf8_lossy(&file.data).into_owned();
        }
        let digest = aix::crypto::sha256(&file.data);
        entries.push(aix::crypto::ManifestEntry {
            path: file.path.clone(),
            size: file.data.len() as u64,
            sha256: digest,
        });
    }
    let package_id = aix::crypto::calculate_package_id(&entries);
    aix::crypto::PackageManifest {
        format: "aix".into(),
        version,
        engine: engine.into(),
        algorithm: "ed25519".into(),
        digest: "sha256".into(),
        key_id: signing_key
            .map(|key| key.public_key().key_id())
            .unwrap_or_default(),
        package_id,
        entries,
    }
}

fn resolve_engine_range(files: &[InputFile], override_engine: Option<&str>) -> Result<String> {
    if let Some(engine) = override_engine {
        return Ok(engine.into());
    }

    let Some(app_json) = files.iter().find(|file| file.path == "app.json") else {
        return Ok("*".into());
    };

    let (utf8, _) = normalize_text_to_utf8("app.json", &app_json.data)?;
    let value: serde_json::Value = serde_json::from_slice(&utf8)
        .map_err(|error| anyhow!("Invalid JSON in app.json: {}", error))?;
    Ok(value
        .as_object()
        .and_then(|object| object.get("engine"))
        .and_then(serde_json::Value::as_str)
        .unwrap_or("*")
        .to_string())
}

/// Validates the AIX app contract before packing.
///
/// A missing `app.json` is a hard error: an AIX package must declare its app
/// configuration. Issues with the `pages` field are returned as non-blocking
/// warnings. Malformed JSON is intentionally not reported here: [`prepare_json`]
/// already rejects invalid `app.json` during packing, so duplicating that
/// failure would only add noise.
fn validate_app_config(files: &[InputFile]) -> Result<Vec<String>> {
    let Some(app_json) = files.iter().find(|file| file.path == "app.json") else {
        return Err(anyhow!("app.json is required but missing"));
    };

    let mut warnings = Vec::new();
    let Ok((utf8, _)) = normalize_text_to_utf8("app.json", &app_json.data) else {
        return Ok(warnings);
    };
    let Ok(value) = serde_json::from_slice::<serde_json::Value>(&utf8) else {
        return Ok(warnings);
    };

    match value.get("pages") {
        None => warnings.push("app.json is missing the required \"pages\" field".to_string()),
        Some(serde_json::Value::Array(pages)) => {
            for page in pages {
                if let Some(path) = page.as_str() {
                    if path.is_empty() {
                        warnings.push("app.json \"pages\" contains an empty path".to_string());
                    }
                } else {
                    warnings.push(format!(
                        "app.json \"pages\" must contain only strings, found {}",
                        page
                    ));
                }
            }
        }
        Some(other) => warnings.push(format!(
            "app.json \"pages\" must be an array of strings, found {}",
            other
        )),
    }

    Ok(warnings)
}

fn validate_paths(files: &[InputFile]) -> Result<()> {
    let mut previous: Option<&str> = None;
    for file in files {
        let path = file.path.as_str();
        if path.is_empty()
            || path.starts_with('/')
            || path.contains('\\')
            || path.starts_with(aix::crypto::METADATA_PREFIX)
            || path
                .split('/')
                .any(|part| part.is_empty() || part == "." || part == "..")
        {
            return Err(anyhow!("invalid package path: {}", path));
        }
        if previous == Some(path) {
            return Err(anyhow!("duplicate package path: {}", path));
        }
        previous = Some(path);
    }
    Ok(())
}

fn prepare_file(
    path: &str,
    data: Vec<u8>,
    optimize: Option<&OptimizeOptions>,
) -> Result<PreparedFile> {
    let extension = path
        .rsplit_once('.')
        .map(|(_, ext)| ext)
        .unwrap_or("")
        .to_ascii_lowercase();
    let enabled = optimize.is_some();

    if extension == "json" {
        return prepare_json(path, &data, optimize.is_some_and(|options| options.json));
    }

    if matches!(extension.as_str(), "js" | "ts") {
        return prepare_script(path, &data);
    }

    if UTF8_TEXT_EXTENSIONS.contains(&extension.as_str()) {
        let (utf8, converted) = normalize_text_to_utf8(path, &data)?;
        return Ok(PreparedFile {
            data: utf8,
            converted_to_utf8: converted,
            optimized: false,
            supported: enabled,
        });
    }

    match (extension.as_str(), optimize) {
        ("png", Some(options)) if options.png => {
            let candidate = optimize_png(&data, options.level)?;
            Ok(smaller_image(data, candidate))
        }
        ("jpg" | "jpeg", Some(options)) if options.jpeg => {
            let candidate = optimize_jpeg(&data, options.level)?;
            Ok(smaller_image(data, candidate))
        }
        _ => Ok(PreparedFile {
            data,
            converted_to_utf8: false,
            optimized: false,
            supported: false,
        }),
    }
}

fn smaller_image(original: Vec<u8>, candidate: Vec<u8>) -> PreparedFile {
    let optimized = candidate.len() < original.len();
    PreparedFile {
        data: if optimized { candidate } else { original },
        converted_to_utf8: false,
        optimized,
        supported: true,
    }
}

fn prepare_json(path: &str, data: &[u8], optimize: bool) -> Result<PreparedFile> {
    let (utf8, converted) = normalize_text_to_utf8(path, data)?;
    let value: serde_json::Value = serde_json::from_slice(&utf8)
        .map_err(|error| anyhow!("Invalid JSON in {}: {}", path, error))?;
    let candidate = if optimize {
        serde_json::to_vec(&value)?
    } else {
        utf8.clone()
    };
    let optimized = optimize && candidate.len() < utf8.len();
    Ok(PreparedFile {
        data: if optimized { candidate } else { utf8 },
        converted_to_utf8: converted,
        optimized,
        supported: true,
    })
}

fn prepare_script(path: &str, data: &[u8]) -> Result<PreparedFile> {
    let (utf8, converted) = normalize_text_to_utf8(path, data)?;
    let source_text = String::from_utf8(utf8.clone())
        .map_err(|_| anyhow!("Failed to decode {} as UTF-8", path))?;
    let minified = minify_script(path, &source_text)?;
    let optimized = minified.as_bytes() != utf8.as_slice();
    Ok(PreparedFile {
        data: if optimized {
            minified.into_bytes()
        } else {
            utf8
        },
        converted_to_utf8: converted,
        optimized,
        supported: true,
    })
}

fn minify_script(path: &str, source_text: &str) -> Result<String> {
    let allocator = Allocator::default();
    let source_type = SourceType::from_path(Path::new(path))
        .map_err(|_| anyhow!("Failed to minify {}: unsupported script extension", path))?;
    let parser_return = Parser::new(&allocator, source_text, source_type).parse();
    if parser_return.panicked {
        return Err(anyhow!("Failed to minify {}: parser panicked", path));
    }
    if let Some(error) = parser_return.diagnostics.first() {
        return Err(anyhow!("Failed to minify {}: {}", path, error));
    }

    let mut program = parser_return.program;
    let minifier = Minifier::new(MinifierOptions {
        mangle: Some(MangleOptions::default()),
        compress: Some(CompressOptions::default()),
    });
    let result = minifier.minify(&allocator, &mut program);

    let generated = Codegen::new()
        .with_options(CodegenOptions::minify())
        .with_scoping(result.scoping)
        .with_private_member_mappings(result.class_private_mappings)
        .build(&program);
    Ok(generated.code)
}

fn optimize_png(data: &[u8], level: u8) -> Result<Vec<u8>> {
    let image = image::load_from_memory_with_format(data, image::ImageFormat::Png)?;
    let compression = match level {
        1 => CompressionType::Fast,
        3 => CompressionType::Best,
        _ => CompressionType::Default,
    };
    let mut output = Vec::new();
    PngEncoder::new_with_quality(&mut output, compression, FilterType::Adaptive).write_image(
        image.as_bytes(),
        image.width(),
        image.height(),
        image.color().into(),
    )?;
    Ok(output)
}

fn optimize_jpeg(data: &[u8], level: u8) -> Result<Vec<u8>> {
    let image = image::load_from_memory_with_format(data, image::ImageFormat::Jpeg)?;
    let quality = match level {
        1 => 90,
        3 => 75,
        _ => 82,
    };
    let mut output = Vec::new();
    JpegEncoder::new_with_quality(&mut output, quality).encode_image(&image)?;
    Ok(output)
}

pub(crate) fn normalize_text_to_utf8(path: &str, data: &[u8]) -> Result<(Vec<u8>, bool)> {
    if let Some(content) = data.strip_prefix(&[0xEF, 0xBB, 0xBF]) {
        return std::str::from_utf8(content)
            .map(|_| (content.to_vec(), true))
            .map_err(|_| anyhow!("Failed to decode {} as UTF-8", path));
    }
    if let Some(content) = data.strip_prefix(&[0xFF, 0xFE]) {
        return decode(path, content, UTF_16LE);
    }
    if let Some(content) = data.strip_prefix(&[0xFE, 0xFF]) {
        return decode(path, content, UTF_16BE);
    }
    if std::str::from_utf8(data).is_ok() {
        return Ok((data.to_vec(), false));
    }

    let (decoded, _, errors) = GB18030.decode(data);
    if !errors {
        return Ok((decoded.into_owned().into_bytes(), true));
    }

    let mut detector = EncodingDetector::new();
    detector.feed(data, true);
    let encoding = detector.guess(None, true);
    if encoding == UTF_8 {
        return Err(anyhow!("Failed to decode {} as UTF-8", path));
    }
    decode(path, data, encoding)
}

fn decode(
    path: &str,
    data: &[u8],
    encoding: &'static encoding_rs::Encoding,
) -> Result<(Vec<u8>, bool)> {
    let (decoded, _, errors) = encoding.decode(data);
    if errors {
        return Err(anyhow!(
            "Failed to convert {} from {} to UTF-8",
            path,
            encoding.name()
        ));
    }
    Ok((decoded.into_owned().into_bytes(), true))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn packs_and_reads_an_artifact() {
        let output = pack(
            vec![InputFile::new("app.json", br#"{ "pages": [] }"#)],
            PackOptions {
                build_id: "test-build".into(),
                engine: Some("^0.14.0".into()),
                optimize: Some(OptimizeOptions::default()),
                signing_key: None,
            },
        )
        .unwrap();
        let reader = aix::AixReader::new(output.data).unwrap();
        assert_eq!(reader.get_version().as_deref(), Some("test-build"));
        let app_json: serde_json::Value =
            serde_json::from_slice(&reader.read_file("app.json").unwrap()).unwrap();
        assert_eq!(app_json["pages"], serde_json::json!([]));
        assert!(app_json.get("engine").is_none());
        assert_eq!(reader.get_engine().as_deref(), Some("^0.14.0"));
        assert!(reader.supports_engine("0.14.9").unwrap());
        assert!(!reader.supports_engine("0.15.0").unwrap());
    }

    #[test]
    fn pack_falls_back_to_app_json_engine() {
        let output = pack(
            vec![InputFile::new(
                "app.json",
                br#"{"pages":[],"engine":"^0.14.0"}"#,
            )],
            PackOptions::new("test-build"),
        )
        .unwrap();

        let reader = aix::AixReader::new(output.data).unwrap();
        assert_eq!(reader.get_engine().as_deref(), Some("^0.14.0"));
        let app_json: serde_json::Value =
            serde_json::from_slice(&reader.read_file("app.json").unwrap()).unwrap();
        assert_eq!(app_json["engine"], "^0.14.0");
    }

    #[test]
    fn pack_defaults_engine_to_any_when_missing_everywhere() {
        let output = pack(
            vec![InputFile::new("app.json", br#"{"pages":[]}"#)],
            PackOptions::new("test-build"),
        )
        .unwrap();

        let reader = aix::AixReader::new(output.data).unwrap();
        assert_eq!(reader.get_engine().as_deref(), Some("*"));
    }

    #[test]
    fn rejects_unsafe_paths() {
        let error = pack(
            vec![InputFile::new("../app.json", b"{}")],
            PackOptions {
                build_id: "test-build".into(),
                engine: Some("*".into()),
                optimize: None,
                signing_key: None,
            },
        )
        .unwrap_err();
        assert!(error.to_string().contains("invalid package path"));
    }

    #[test]
    fn rejects_reserved_metadata_paths() {
        for path in [
            aix::crypto::MANIFEST_PATH,
            "META-INF/aix/custom-metadata.json",
        ] {
            let error = pack(
                vec![InputFile::new(path, b"{}")],
                PackOptions::new("test-build"),
            )
            .unwrap_err();
            assert!(error.to_string().contains("invalid package path"));
        }
    }

    #[test]
    fn signs_and_verifies_an_artifact() {
        let key = aix::crypto::PrivateKey::from_seed([9; 32]);
        let output = pack(
            vec![InputFile::new("app.json", br#"{"pages":[]}"#)],
            PackOptions {
                build_id: "signed-build".into(),
                engine: Some(">=0.14.0".into()),
                optimize: None,
                signing_key: Some(&key),
            },
        )
        .unwrap();
        let reader = aix::AixReader::new(output.data).unwrap();
        let report = reader.verify_signature(&key.public_key()).unwrap();
        assert_eq!(report.version, "signed-build");
        assert_eq!(report.engine, ">=0.14.0");
        assert_eq!(report.entry_count, 2);
    }

    #[test]
    fn strips_utf8_bom_before_parsing_json() {
        let mut data = vec![0xEF, 0xBB, 0xBF];
        data.extend_from_slice(br#"{"pages":[]}"#);

        let prepared = prepare_json("app.json", &data, false).unwrap();

        assert_eq!(prepared.data, br#"{"pages":[]}"#);
        assert!(prepared.converted_to_utf8);
    }

    #[test]
    fn strips_utf16_bom_during_conversion() {
        let mut data = vec![0xFF, 0xFE];
        for unit in "const ready = true;".encode_utf16() {
            data.extend_from_slice(&unit.to_le_bytes());
        }

        let (normalized, converted) = normalize_text_to_utf8("app.js", &data).unwrap();

        assert_eq!(normalized, b"const ready = true;");
        assert!(converted);
    }

    #[test]
    fn packs_js_and_ts_with_default_minification() {
        let output = pack(
            vec![
                InputFile::new("app.json", br#"{"pages":[]}"#),
                InputFile::new(
                    "scripts/app.js",
                    b"function demo(value) { return value + 1; }\n",
                ),
                InputFile::new("scripts/types.ts", b"export const total: number = 1 + 2;\n"),
            ],
            PackOptions::new("test-build"),
        )
        .unwrap();

        let reader = aix::AixReader::new(output.data).unwrap();
        let js_output = String::from_utf8(reader.read_file("scripts/app.js").unwrap()).unwrap();
        assert!(js_output.starts_with("function demo("));
        assert!(js_output.contains("return "));
        assert!(!js_output.contains("value"));
        assert!(js_output.len() < "function demo(value) { return value + 1; }\n".len());

        let ts_output = String::from_utf8(reader.read_file("scripts/types.ts").unwrap()).unwrap();
        assert_eq!(ts_output, "export const total:number=3;");

        let js_report = output
            .report
            .files
            .iter()
            .find(|file| file.path == "scripts/app.js")
            .unwrap();
        assert_eq!(js_report.status, OptimizeStatus::Optimized);
        assert!(!js_report.converted_to_utf8);

        let ts_report = output
            .report
            .files
            .iter()
            .find(|file| file.path == "scripts/types.ts")
            .unwrap();
        assert_eq!(ts_report.status, OptimizeStatus::Optimized);
        assert!(!ts_report.converted_to_utf8);
    }

    #[test]
    fn reports_script_parse_errors_with_file_path() {
        let error = pack(
            vec![
                InputFile::new("app.json", br#"{"pages":[]}"#),
                InputFile::new("scripts/broken.ts", b"export const value: = 1;\n"),
            ],
            PackOptions::new("test-build"),
        )
        .unwrap_err();

        let message = error.to_string();
        assert!(message.contains("Failed to minify scripts/broken.ts"));
        assert!(message.contains("scripts/broken.ts"));
    }

    #[test]
    fn collector_and_direct_pack_share_script_minification() {
        let files = vec![
            InputFile::new("app.json", br#"{"pages":[]}"#),
            InputFile::new(
                "pages\\index.ts",
                b"export const page = () => ({ ready: true });\n",
            ),
        ];

        let direct = pack(
            vec![
                InputFile::new("app.json", br#"{"pages":[]}"#),
                InputFile::new(
                    "pages/index.ts",
                    b"export const page = () => ({ ready: true });\n",
                ),
            ],
            PackOptions::new("test-build"),
        )
        .unwrap();
        let collected = collector::pack_source_files(
            files,
            &collector::CollectOptions::default(),
            PackOptions::new("test-build"),
        )
        .unwrap();

        let direct_reader = aix::AixReader::new(direct.data).unwrap();
        let collected_reader = aix::AixReader::new(collected.data).unwrap();
        assert_eq!(
            direct_reader.read_file("pages/index.ts").unwrap(),
            collected_reader.read_file("pages/index.ts").unwrap()
        );
    }

    #[test]
    fn pack_with_progress_reports_each_processed_file() {
        let mut reported_paths = Vec::new();

        let output = pack_with_progress(
            vec![
                InputFile::new("app.json", br#"{"pages":[]}"#),
                InputFile::new("scripts/app.ts", b"export const total: number = 1 + 2;\n"),
            ],
            PackOptions::new("test-build"),
            |event| {
                if let PackProgressEvent::FileFinished { report } = event {
                    reported_paths.push(report.path);
                }
                Ok(())
            },
        )
        .unwrap();

        let output_paths: Vec<String> = output
            .report
            .files
            .iter()
            .map(|file| file.path.clone())
            .collect();
        assert_eq!(reported_paths, output_paths);
    }

    #[test]
    fn rejects_when_app_json_is_missing() {
        let error = pack(
            vec![InputFile::new("scripts/app.js", b"function demo() {}\n")],
            PackOptions::new("test-build"),
        )
        .unwrap_err();

        assert_eq!(error.to_string(), "app.json is required but missing");
    }

    #[test]
    fn pack_with_progress_rejects_missing_app_json() {
        let error = pack_with_progress(
            vec![InputFile::new("scripts/app.js", b"function demo() {}\n")],
            PackOptions::new("test-build"),
            |_| Ok(()),
        )
        .unwrap_err();

        assert_eq!(error.to_string(), "app.json is required but missing");
    }

    #[test]
    fn warns_when_pages_field_is_missing() {
        let output = pack(
            vec![InputFile::new(
                "app.json",
                br#"{"window":{"navigationBarTitleText":"App"}}"#,
            )],
            PackOptions::new("test-build"),
        )
        .unwrap();

        assert_eq!(
            output.warnings,
            vec!["app.json is missing the required \"pages\" field".to_string()]
        );
    }

    #[test]
    fn warns_when_pages_is_not_an_array() {
        let output = pack(
            vec![InputFile::new(
                "app.json",
                br#"{"pages":"pages/index/index"}"#,
            )],
            PackOptions::new("test-build"),
        )
        .unwrap();

        assert_eq!(
            output.warnings,
            vec![
                "app.json \"pages\" must be an array of strings, found \"pages/index/index\""
                    .to_string()
            ]
        );
    }

    #[test]
    fn warns_when_pages_contains_non_string_entries() {
        let output = pack(
            vec![InputFile::new(
                "app.json",
                br#"{"pages":["pages/index/index", 42, ""]}"#,
            )],
            PackOptions::new("test-build"),
        )
        .unwrap();

        assert_eq!(
            output.warnings,
            vec![
                "app.json \"pages\" must contain only strings, found 42".to_string(),
                "app.json \"pages\" contains an empty path".to_string(),
            ]
        );
    }

    #[test]
    fn has_no_warnings_for_valid_app_config() {
        let output = pack(
            vec![InputFile::new(
                "app.json",
                br#"{"pages":["pages/index/index"],"window":{"navigationBarTitleText":"App"}}"#,
            )],
            PackOptions::new("test-build"),
        )
        .unwrap();

        assert!(output.warnings.is_empty());
    }

    #[test]
    fn chooses_compression_method_per_extension() {
        assert_eq!(
            compression_method_for("app.json"),
            zip::CompressionMethod::Deflated
        );
        assert_eq!(
            compression_method_for("pages/index/index.ink"),
            zip::CompressionMethod::Deflated
        );
        assert_eq!(
            compression_method_for("images/cover.png"),
            zip::CompressionMethod::Stored
        );
        assert_eq!(
            compression_method_for("images/cover.jpg"),
            zip::CompressionMethod::Stored
        );
        assert_eq!(
            compression_method_for("images/cover.jpeg"),
            zip::CompressionMethod::Stored
        );
    }

    #[test]
    fn deflates_text_entries_and_round_trips() {
        let ink = "repeated padding text ".repeat(200);
        let output = pack(
            vec![
                InputFile::new("app.json", br#"{"pages":[]}"#),
                InputFile::new("pages/index/index.ink", ink.clone()),
            ],
            PackOptions::new("test-build"),
        )
        .unwrap();

        // The reader re-verifies CRC + uncompressed size, so a successful read
        // proves the DEFLATE round-trip is intact end to end.
        let reader = aix::AixReader::new(output.data).unwrap();
        assert_eq!(
            reader.read_file("pages/index/index.ink").unwrap(),
            ink.into_bytes()
        );

        let entry = reader
            .list()
            .iter()
            .find(|entry| entry.name == "pages/index/index.ink")
            .unwrap();
        assert!(entry.compressed_size < entry.size);
    }
}
